export const REQUEST_DATA_COURSES = 'REQUEST_DATA_COURSES'
export const SUCCESS_DATA_COURSES = 'SUCCESS_DATA_COURSES'
export const ERROR_DATA_COURSES = 'ERROR_DATA_COURSES'
export const SET_COURSE_SELECTED = 'SET_COURSE_SELECTED'
